---
title: 'ECON-613 HW #1'
author: "Min Chul Kim"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

Here, I am calling all the packages I am going to use in this assignment.
```{r, Libraries, include = FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(purrr)
library(stringr)
library(readr)
library(tidyr)
```

Here, I read data.
```{r, Reading Data}
#Reading Data
datjss <- read_csv("~/Downloads/dat (1) 2/datjss.csv")
datsss <- read_csv("~/Downloads/dat (1) 2/datsss.csv")
datstu <- read_csv("~/Downloads/dat (1) 2/datstu.csv")
```

Here, I am creating a table function which I will use later to present obtained statistics in a nice format.
```{r}
table = function(df, dig, capt){
  kable(df, 
        digits = dig, 
        booktabs = TRUE, 
        caption = capt
        ) 
}
```

## Exercise 1

```{r, Exercise 1}
#Number of School
School_Num = datstu[, paste("schoolcode", 1:6, sep = "")] %>%
  unlist() %>%
  unique() %>%
  na.omit() %>%
  length()

#Number of Program
Programs_Num = datstu[, paste("choicepgm", 1:6, sep = "")] %>%
  unlist() %>%
  unique() %>%
  na.omit() %>%
  length()

#Number of Choices
School = datstu[, paste("schoolcode", 1:6, sep = "")]
Choices = datstu[, paste("choicepgm", 1:6, sep = "")] 

Total_Choices = data.frame(
  Choices1 = paste(School$schoolcode1, Choices$choicepgm1),
  Choices2 = paste(School$schoolcode2, Choices$choicepgm2),
  Choices3 = paste(School$schoolcode3, Choices$choicepgm3),
  Choices4 = paste(School$schoolcode4, Choices$choicepgm4),
  Choices5 = paste(School$schoolcode1, Choices$choicepgm5),
  Choices6 = paste(School$schoolcode1, Choices$choicepgm6)
) %>%
  unlist() %>%
  unique() %>%
  na.omit() %>%
  length()

#Missing Data
Missing_Test = datstu$score %>% 
  summary() %>%
  .["NA's"] %>%
  as.integer()
  
#Apply to the Same School
No_NA_School = apply(School, 1, FUN = na.omit) %>%
  map(length) %>%
  unlist() 

Num_School_Applied = apply(School, 1, FUN = unique) %>%
  map(na.omit) %>%
  map(length) %>%
  unlist()

Same_School = ifelse(Num_School_Applied < No_NA_School, "Yes", "No") %>%
  as.data.frame()

#Apply to less than 6 Choices
Num_Choices_Applied = apply(Choices, 1, na.omit) %>%
  map(length) %>%
  unlist() 

Less_Choices = ifelse(Num_Choices_Applied < 6, "Yes", "No") %>%
  as.data.frame()
colnames(Less_Choices) = "Apply to less than 6 programs?"

#Dataframe of Number of Students, Number of Schools, Number of Programs, etc.
Exercise1_df = data_frame(
  nrow(datstu),
  School_Num,
  Programs_Num,
  Total_Choices,
  Missing_Test
)
colnames(Exercise1_df) = c("Num of Student", "Num of School", "Num of Programs",
                           "Number of Choices", "Missing Test Score")

#Summary Tables
table(Exercise1_df, 4, 
      "Summary Table of Statistics Other Than Same School and Less than 6 Choices")
table(Same_School, 4, "Table of Apply to the Same School")
table(Less_Choices, 4, "Table of Apply to less than 6 Choices")
```

## Exercise 2

```{r, Exercise 2}
School_Level_Dataset = data.frame(
  Choices1 = paste(School$schoolcode1, Choices$choicepgm1, sep = "_"),
  Choices2 = paste(School$schoolcode2, Choices$choicepgm2, sep = "_"),
  Choices3 = paste(School$schoolcode3, Choices$choicepgm3, sep = "_"),
  Choices4 = paste(School$schoolcode4, Choices$choicepgm4, sep = "_"),
  Choices5 = paste(School$schoolcode1, Choices$choicepgm5, sep = "_"),
  Choices6 = paste(School$schoolcode1, Choices$choicepgm6, sep = "_")
) %>%
  unlist() %>%
  unique() %>%
  na.omit() %>% 
  as.data.frame()
colnames(School_Level_Dataset) = "School_Programs"

School_and_Program = School_Level_Dataset %>% 
  separate(School_Programs, c("School", "Program"), "_")

catalog = datsss %>% group_by(schoolcode) %>% 
  select(schoolcode, sssdistrict, ssslat, ssslong) %>% 
  unique() %>% na.omit() %>% arrange(schoolcode) %>% as.data.frame() 

codes = dist = lat = long = rep(NA, nrow(School_Level_Dataset))
for(i in 1:nrow(School_Level_Dataset)){
  
  codes[i] = School_and_Program[, "School"][i] 
  
  dist[i] = catalog %>% filter(schoolcode == codes[i]) %>% select(sssdistrict)
  lat[i] = catalog %>% filter(schoolcode == codes[i]) %>% select(ssslat)
  long[i] = catalog %>% filter(schoolcode == codes[i]) %>% select(ssslong)
}

datstu2 = datstu %>%
  mutate(
  SchoolProgram1 = paste(School$schoolcode1, 
                         Choices$choicepgm1, sep = "_") %>% as.character(),
  SchoolProgram2 = paste(School$schoolcode2, 
                         Choices$choicepgm2, sep = "_") %>% as.character(),
  SchoolProgram3 = paste(School$schoolcode3, 
                         Choices$choicepgm3, sep = "_") %>% as.character(),
  SchoolProgram4 = paste(School$schoolcode4, 
                         Choices$choicepgm4, sep = "_") %>% as.character(),
  SchoolProgram5 = paste(School$schoolcode1, 
                         Choices$choicepgm5, sep = "_") %>% as.character(),
  SchoolProgram6 = paste(School$schoolcode1, 
                         Choices$choicepgm6, sep = "_") %>% as.character()
  )

is_not_integer0 = function(x){
  if(!identical(x, integer(0))){
    return(TRUE)
  } else{
    return(FALSE)
  }
}

code = mini = avg = admit = rep(NA, nrow(School_Level_Dataset))
for(i in 1:nrow(School_Level_Dataset)){
  
  code[i] = School_Level_Dataset[,"School_Programs"][i] %>% as.character()
  
  mini[i] = datstu2 %>%
    filter(code[i] == SchoolProgram1 |
            code[i] == SchoolProgram2 |
            code[i] == SchoolProgram3 |
            code[i] == SchoolProgram4 |
            code[i] == SchoolProgram5 |
            code[i] == SchoolProgram6) %>% 
    select(score) %>% na.omit() %>% map(as.integer) %>% 
    map_if(is_not_integer0, min) %>% ifelse(. == "integer(0)", NA, .)
    
  avg[i] = datstu2 %>%
    filter(code[i] == SchoolProgram1 |
            code[i] == SchoolProgram2 |
            code[i] == SchoolProgram3 |
            code[i] == SchoolProgram4 |
            code[i] == SchoolProgram5 |
            code[i] == SchoolProgram6) %>% 
    select(score) %>% na.omit() %>% map(as.integer) %>% 
    map_if(is_not_integer0, mean) %>% ifelse(. == "integer(0)", NA, .)
  
  admit[i] = datstu2 %>%
    filter(code[i] == SchoolProgram1 |
            code[i] == SchoolProgram2 |
            code[i] == SchoolProgram3 |
            code[i] == SchoolProgram4 |
            code[i] == SchoolProgram5 |
            code[i] == SchoolProgram6) %>% 
    nrow() %>% map(as.integer)
}


School_Level_Dataset = School_Level_Dataset %>%
  mutate(
    schoolcode = School_and_Program[,"School"],
    program = School_and_Program[,"Program"],
    district = dist,
    latitude = lat, 
    longitude = long,
    cutoff = mini,
    quality = avg,
    size = admit
  ) %>% 
  arrange(schoolcode) %>%
  select(-c(schoolcode, program))




```

## Exercise 3

```{r, Exericse 3}
dist = function(i, j){
  return(sqrt( (69.172 * (datsss$ssslong[j] - datjss$point_x[i]) * 
           cos(datjss$point_y[i] / 57.3))^2 +
          ( 69.172 *(datsss$ssslat[j] - datjss$point_y[i]))^2 ))
}

dist_df = data.frame(
  rep( seq(datjss$X1) , each = length(datsss$X1) ),
  rep( seq(datsss$X1), length(datjss$X1) ),
  NA,
  rep( datjss$jssdistrict, each = length(datsss$X1) ),
  rep( datsss$sssdistrict, length(datjss$X1) )
)
colnames(dist_df) =
  c("jss_index", "sss_index", "Distance", "jss District", "sss District")

dist_df$Distance = map2(dist_df[, 1], dist_df[, 2], dist)

dist_df = dist_df %>%
  select("jss District", "sss District", "Distance")
```

## Exercise 4